### PR TITLE
Update SQL export with latest test DB export, less camper data

### PR DESCRIPTION
**Pull request by brianeroth**

### CODE REVIEW

**Comment by JonahZW** [comment]
I just went in and anonymized the camper data, added an admin user for the db, and made a few other small modifications to the file. I tested it locally and everything worked as expected, but not a horrible idea for someone else to take it for a spin, too

**Review by dlobron — CHANGES_REQUESTED** [review]
The code looks good! The only issue I spotted when I tested is that many campers don't have enough chugim in order to do a legal submit. For example, when I try to set prefs for "Severus Snape", I get errors because some of the choice bubbles have less than 3 choices, but there are not enough chugim in the given chug/session to do the assignment (see image).

I think we can fix this by updating chugim so they are available in more session/block combos. Will that be doable, or will it drive you nuts to make all those edits? If the edits are too much, we could just reduce the number of campers to 2 or 3, and edit just those ones. BTW, I love the name replacements. :)

Screenshot 2024-01-31 at 8 15 46 AM

**Comment by JonahZW** [comment]
Good catch, sorry about that! I believe it should now be fixed - I pulled the chug list from the DC database and corrected the edot_for_chug table entries so it should work now (I also added sample departments and names for the chugim, too)

**Comment by dlobron** [comment]
Thanks, Jonah- it's working great for me now! I'll merge this shortly.

**Pull request merged**
