### PR TITLE
Setup for SSL certs

### PR DESCRIPTION
**Pull request by brianeroth**

### CODE REVIEW

**Comment by brianeroth** [comment]
@dlobron This PR adds configuration files so we can generate SSL certificates for all the new websites

**Comment by dlobron** [comment]
@brianeroth  ,this all looks good to me. Can you tell me what the scripts are for, and how to use them?  If you don't mind adding a short paragraph to the README.md, it would be ideal, but email to me is fine too. :)

**Comment by brianeroth** [comment]
> @brianeroth ,this all looks good to me. Can you tell me what the scripts are for, and how to use them? If you don't mind adding a short paragraph to the README.md, it would be ideal, but email to me is fine too. :)

@dlobron These scripts are pretty much set-it-and-forget-it, and shouldn't really need to be updated. Elastic Beanstalk will automatically execute these scripts on code deploy (since it looks in these directories for any scripts), and renew the SSL certificate on a schedule. These scripts use certbot and Let's Encrypt to generate SSL certificates for each of the domains, and serve traffic over https rather than http.

**Comment by dlobron** [comment]
@brianeroth , thank you- that makes sense!  Thank you for adding these- it's great to have HTTPS.

**Pull request merged**
